import pandas as pd
import pandas_ta as ta
import os

def build_feature_store(file_path):
    """
    Reads a stock's OHLCV data and calculates all major technical indicators.
    Returns the dataframe with the new indicator columns appended.
    """
    try:
        df = pd.read_csv(file_path, index_col='Date', parse_dates=True)

        # We need at least 200 days of data for a 200 SMA
        if len(df) < 200:
            print(f"  [!] Skipping {file_path}: Not enough data ({len(df)} rows)")
            return None

            # 1. Trend Indicators (Moving Averages)
        df.ta.sma(length=20, append=True)
        df.ta.sma(length=50, append=True)
        df.ta.sma(length=150, append=True)
        df.ta.sma(length=200, append=True)

        # 2. Momentum Indicators
        df.ta.rsi(length=14, append=True)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)

        # Rename MACD for easier querying
        df.rename(columns={'MACD_12_26_9': 'MACD', 'MACDh_12_26_9': 'MACD_Histogram'}, inplace=True)

        # 3. Custom Features (FIXED: Added min_periods to prevent NaN wipeout)
        df['High_52week'] = df['High'].rolling(window=252, min_periods=150).max()
        df['Low_52week'] = df['Low'].rolling(window=252, min_periods=150).min()
        df['Volume_SMA_20'] = df['Volume'].rolling(window=20, min_periods=10).mean()

        # Drop the initial rows that don't have enough data for the 200 SMA
        df.dropna(inplace=True)

        # Double check that we still have data left to analyze
        if df.empty:
            print(f"  [!] {file_path} became empty after dropping NaNs.")
            return None

        return df

    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None


def run_strategy_engine(query_string, data_dir="stock_data"):
    """
    Loops through all stocks, builds the feature store, and evaluates 'today's' data
    against the AI-generated query string.
    """
    if not os.path.exists(data_dir):
        print(f"Error: Directory '{data_dir}' not found. Run Phase 2 first.")
        return []

    print(f"\nEvaluating Strategy: [ {query_string} ]")
    print("Building feature store and scanning stocks...\n")

    passed_stocks = []

    # Loop through all CSV files downloaded in Phase 2
    for filename in os.listdir(data_dir):
        if filename.endswith(".csv"):
            ticker = filename.replace(".csv", "")
            file_path = os.path.join(data_dir, filename)

            # 1. Calculate all indicators
            df = build_feature_store(file_path)

            if df is not None and not df.empty:
                # 2. Isolate "Today" (the very last row of the dataset)
                latest_data = df.iloc[[-1]]

                try:
                    # 3. The Magic: Pandas evaluates the string logic against the latest row
                    result = latest_data.query(query_string)

                    # If the result dataframe is not empty, the stock passed the test!
                    if not result.empty:
                        print(f"  [+] PASS: {ticker}")
                        passed_stocks.append(ticker)
                except Exception as e:
                    print(f"  [!] Invalid Query Syntax for {ticker}: {e}")
                    break # Break out if the query itself is fundamentally broken

    return passed_stocks

# --- Main Execution ---
if __name__ == "__main__":
    # In the next phase, this string will be generated by an LLM based on your natural language prompt.
    # For now, let's test it with a classic Mark Minervini Trend Template rule:
    # "Price is above 50 SMA, 50 SMA is above 150 SMA, 150 SMA is above 200 SMA, and Price is within 25% of 52-week high"

    test_query = "Close > SMA_50 and SMA_50 > SMA_150 and SMA_150 > SMA_200 and Close >= (High_52week * 0.75)"
    # test_query = "Close < SMA_200"

    print("--- Starting Technical AI Strategy Engine ---")
    winners = run_strategy_engine(test_query)

    print(f"\n--- Scan Complete ---")
    print(f"Out of all fundamental stocks, only {len(winners)} passed the technical strategy.")
    print(f"Final Watchlist: {winners}")

    # Save the ultimate winners
    if winners:
        pd.DataFrame({"Ticker": winners}).to_csv("step3_final_shortlist.csv", index=False)
        print("Saved to step3_final_shortlist.csv")